const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.filechooser,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.TextBox,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Text.Exps.TextWidth,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Text.Acts.SetWrapping,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot
	];
};
self.C3_JsPropNameTable = [
	{bkg: 0},
	{Mouse: 0},
	{Touch: 0},
	{UserImage: 0},
	{ImageChooser: 0},
	{speed: 0},
	{w: 0},
	{h: 0},
	{Balloon: 0},
	{Keyboard: 0},
	{Pin: 0},
	{BalloonText: 0},
	{NoteInput: 0},
	{SendBtn: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{ColorBtn: 0},
	{NameInput: 0},
	{BdayInput: 0},
	{frame1: 0},
	{birthFo: 0},
	{message: 0},
	{SaveBtn: 0},
	{Audio: 0},
	{playmusic: 0},
	{Browser: 0},
	{selR: 0},
	{selG: 0},
	{selB: 0},
	{lastNote: 0},
	{selFrame: 0},
	{userName: 0},
	{userBday: 0},
	{MusicOn: 0}
];

self.InstanceType = {
	bkg: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	UserImage: class extends self.ISpriteInstance {},
	ImageChooser: class extends self.IFileChooserInstance {},
	Balloon: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	BalloonText: class extends self.ITextInstance {},
	NoteInput: class extends self.ITextInputInstance {},
	SendBtn: class extends self.ISpriteInstance {},
	ColorBtn: class extends self.ISpriteInstance {},
	NameInput: class extends self.ITextInputInstance {},
	BdayInput: class extends self.ITextInputInstance {},
	frame1: class extends self.ISpriteInstance {},
	birthFo: class extends self.ISpriteInstance {},
	message: class extends self.ITextInstance {},
	SaveBtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	playmusic: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {}
}